# 公共配置文件
server:
  port: 8301
  address: 0.0.0.0
api:
  base-url: http://localhost:8201  # 本地开发环境
spring:
  profiles:
    active: dev
  cloud:
    gateway:
      default-filters:
        # - AddResponseHeader=source, leng
        - AddResponseHeader=Content-Type, application/json;charset=UTF-8
      routes:
        - id: api_route
          uri: http://localhost:8201
          predicates:
            - Path=/api/**
#             - id: add_request_header_route
#          uri: http://localhost:8201
#          predicates:
#            - Path=/api/**
#          filters:
#            - AddRequestHeader=leng, swag
#            - AddRequestParameter=name, dog
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/fallback
#        - id: leng-fallback
#          uri: https://www.baidu.com
#          predicates:
#            - Path=/fallback
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    qosPort: 33333
    name: dubbo-springboot-demo-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848


